# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('donation', 'Донорство яйцеклеток'), ('surrogacy', 'Суррогатное материнство')], max_length=20, verbose_name='Тип заявки')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вопрос FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('hero', 'Главный баннер (Hero)'), ('about', 'Блок «О нас»'), ('donation', 'Блок «Донорство»'), ('surrogacy', 'Блок «Суррогатное материнство»'), ('story_1', 'История 1 (Елена)'), ('story_2', 'История 2 (Мария)')], help_text='Уникальный код изображения на сайте', max_length=50, unique=True, verbose_name='Код')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Подпись (alt)')),
                ('url_override', models.URLField(blank=True, help_text='Если указано, будет использоваться вместо загруженного файла', max_length=500, verbose_name='Внешняя ссылка (если не загружать файл)')),
            ],
            options={
                'verbose_name': 'Изображение сайта',
                'verbose_name_plural': 'Изображения сайта',
            },
        ),
    ]
